# Exception
* An exception is an indication of a problem that occurs during a program's execution. It would disrupt the normal flow of instructions
```java
public static void main(String[] args) {
  Scanner scanner = new Scanner(System.in);
  System.out.print("Enter an integer numerator: ");
  int numerator = scanner.nextInt();
  System.out.print("Enter an integer denominator: ");
  int denominator = scanner.nextInt();
  int result = quotient(numerator, denominator);
  System.out.printf("Result: %d / %d = %d\n", numerator, denominator, result);
  scanner.close();
  }
public static int quotient(int numerator, int denominator) {
  return numerator / denominator;
}
```

## Three executions of the program
```
Enter an integer numerator: 3
Enter an integer denominator: 2
Result: 3 / 2 = 1
```
* A normal execution, where the result is calculated correctly
```
Enter an integer numerator: 3
Enter an integer denominator: 0
Exception in thread "main" java.lang.ArithmeticException: / by zero
at ExceptionExample.quotient(ExceptionExample.java:15)
at ExceptionExample.main(ExceptionExample.java:10)
```
* An execution where the "/ by zero" execption is thrown and the program terminates
```
Enter an integer numerator: 3
Enter an integer denominator: a
Exception in thread "main" java.util.InputMismatchException
at java.util.Scanner.throwFor(Unknown Source)
at java.util.Scanner.next(Unknown Source)
at java.util.Scanner.nextInt(Unknown Source)
at java.util.Scanner.nextInt(Unknown Source)
at ExceptionExample.main(ExceptionExample.java:9)
```
* An execution where the "InputMismatch" exception is thrown and the program terminates

## Exception handing
* An exception would disrupt program execution flows
* Exception handling is a nice reature of the Java language that can help you write robust and fault-tolerant programs
* With exception handling, a program can continue executing (rather than terminating) after dealing with a problem. It is very useful in mission-critical or business-critical computing

## try-catch statement syntax
```java
try {
  // code that might throw an exception
} catch( ExceptionType1 e1 ) {
  // code that handles type1 exception
} catch( ExceptionType2 e2 ) {
  // code that handles type2 exception
} catch( ExceptionType3 e3 ) {
  // code that handles type3 exception
} ...
```
At least one catch block or finally block must immediately follow the try block ("immediately" means no content in between)

## Handling the two exceptions
```java
import java.util.InputMismatchException;
import java.util.Scanner;

public class ExceptionExample {
	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
		boolean continueLoop = true;
		do {
			try {
				System.out.print("Enter an integer numerator: ");
				int numerator = scanner.nextInt();
				System.out.print("Enter an integer denominator: ");
				int denominator = scanner.nextInt();
				int result = quotient(numerator, denominator);
				System.out.printf("Result: %d / %d = %d\n", numerator, denominator, result);
				scanner.close();
				continueLoop = false;
			} catch (InputMismatchException inputMismatchException) {
				System.err.printf("Exception: %s\n", inputMismatchException);
				scanner.nextLine(); // discard input so user can try again
			} catch (ArithmeticException arithmeticException) {
				System.err.printf("Exception: %s\n", arithmeticException);
			}
		} while (continueLoop);
	}

	public static int quotient(int numerator, int denominator) {
		return numerator / denominator;
	}
}
```

## Checked vs. Unchecked Exceptions
* Java distinguishes between checked exceptions and unchecked exceptions
* All exception types that are direct or indirect subclasses of the class *RuntimeException* are unchecked exceptions
* Unchecked exceptions are typically caused by defects in your program's code. Examples include *ArithmeticException, InputMismatchException, NullPointerException*
* All exception types that inherit from the class the class `Exception` but not `RuntimeException` are checked exceptions
* Checked exceptions are typically caused by conditions that are not under the control of the program. For example, in file processing, the program can't open a file because the file does not exist
* Unlike unchecked exceptions, checked exceptions cannot be ignored at the time of compilation (must be taken care of by programmers). Java compiler enforces a catch-or-declare requirement for checked exceptions

### Example: Unchecked Exceptions
```java
public static void main(String[] args) {
  Scanner scanner = new Scanner(System.in);
  System.out.print("Enter an integer numerator: ");
  int numerator = scanner.nextInt(); // potential runtime exception
  System.out.print("Enter an integer denominator: ");
  int denominator = scanner.nextInt(); // potential runtime exception
  int result = quotient(numerator, denominator);
  System.out.printf("Result: %d / %d = %d\n", numerator, denominator, result);
  scanner.close();
}
public static int quotient(int numerator, int denominator) {
  return numerator / denominator; // potential runtime exception
}
```

###Example: Checked Exceptions
```java
public static void main(String[] args) {
  File f = new File("test.txt");
  FileReader reader = new FileReader(f);
  reader.close();
}
```
* The catch solution
```java
public static void main(String[] args) {
  try {
    File f = new File("test.txt");
    FileReader reader = new FileReader(f);
    reader.close();
  } catch(FileNotFoundException e) {
    // handle file not found exception
  } catch(IOException e) {
    // handle IO exception
  }
}
```
* The declare solution
```java
public static void main(String[] args) throws FileNotFoundException, IOException {
  File f = new File("test.txt");
  FileReader reader = new FileReader(f);
  reader.close();
}
```
`The throws clause declares the exceptions that might be thrown when the mehtod is executed and let the callers handle the exceptions`

## final block
```java
try {
  // protected code
}
  // catch blocks (optional)
finally {
  // always execute
  //when try block exits
}
```
* finally is useful for more than just exception handling. It prevents cleanup code from being accidentally bypassed by statement like return. `Putting cleanup code in a finally block is good practice`, even when no exceptions are anticipated
* The finally block ensures that the used resource is closed regardless of whether the try statement completes normally or abruptly
```java
public String readFirstLineFromFile(String path) throws IOException {
  BufferedReader br;
  try {
    br = new BufferedReader(new FileReader(path));
    return br.readLine();
  } finally {
    if (br != null)
    br.close();
  }
}
```

## Assertions
* When implementing and debugging a class, it's sometimes useful to state conditions that should be true at a particular point in a method
* These conditions, called assertins, help ensure a program's correctness by catching potential bugs (such as logic errors) during development
* Java has two versions of assert statement:
  - assert expression; throws an AssertionError if expression is false
  - assert expression1 : expression2; throws an AssertionError with expression2 as the error message if expression1 is false 
```java
public class AssertionExample {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);
		System.out.print("Enter a number between 0 and 10: ");
		int number = input.nextInt();
		assert (number >= 0 && number <= 10) : "bad number: " + number;
	}
}
```
Output
```
Enter a number between 0 and 10: 12
Exception in thread "main" java.lang.AssertionError: bad number: 12
at AssertionExample.main(AssertionExample.java:8)
```
